t1004. Индикатор оценки + отображение оценки пользователя
MeeWeeL/AnimeListOnKotlin pull request #12
Opened 2022-08-13 16:58 UTC by MeeWeeL

2022-08-15 19:10 UTC, Elena01001 requested changes
CamelCase instead of snake

2022-08-15 19:10 UTC, Elena01001 commented on app/src/main/res/values-ru/strings.xml
> +    <string name="yourRate">Твоя оценка</string>
Почему-то все названия идут через_ (snake case), а именно здесь camel

2022-08-15 19:18 UTC, SquareBrains approved these changes, later dismissed
Всё хорошо

2022-08-16 17:41 UTC, MeeWeeL commented on app/src/main/res/values-ru/strings.xml
> +    <string name="yourRate">Твоя оценка</string>
Исправил

2022-08-16 19:54 UTC, Elena01001 approved these changes

2022-08-18 08:53 UTC, SquareBrains approved these changes

2022-08-18 11:17 UTC, merged