t1013. Перевела Mapping на extension функции
MeeWeeL/AnimeListOnKotlin pull request #15
Opened 2022-08-16 16:49 UTC by Elena01001

Старый код закомментила, не стала удалять, вдруг чего

2022-08-16 17:27 UTC, MeeWeeL requested changes

2022-08-16 17:27 UTC, MeeWeeL commented on app/src/main/java/com/meeweel/anilist/data/room/Mapping.kt
> +/*fun convertResponseToEntity(response: AnimeResponse) : Entity {
Комментарии удаляй. Старые версии мы можем посмотреть в старих версиях

2022-08-16 17:27 UTC, MeeWeeL commented on app/src/main/java/com/meeweel/anilist/data/room/LocalRepositoryImpl.kt
> +    /*override fun getAnimeById(id: Int): Anime {
Комментарии удаляй

2022-08-16 17:27 UTC, MeeWeeL commented on app/src/main/java/com/meeweel/anilist/data/retrofit/AnimeSynchronizer.kt
> +        repository.insertLocalEntity(list.map { it.toEntity() })
Лучше сделать функцию расширения самого листа респонсов тоже, что бы получилось list.toEntityList(). По примеру https://github.com/MeeWeeL/Kanban-Board/blob/master/data/src/main/java/com/meeweel/data/responsemodels/TaskResponse.kt

2022-08-16 17:27 UTC, MeeWeeL commented on app/src/main/java/com/meeweel/anilist/data/room/Mapping.kt
> +/*fun convertEntityToAnilist(entityList: List<Entity>): List<Anime> {
Комментарии удаляй

2022-08-16 17:27 UTC, MeeWeeL commented on app/src/main/java/com/meeweel/anilist/data/room/Mapping.kt
> +    if (isRussian) {
Придерживайся общего стиля. Если указываешь имена переменных, которым присваиваешь значения, то указывай их везде. В том числе и перед Иф или Вен. Пример https://github.com/MeeWeeL/Kanban-Board/blob/master/data/src/main/java/com/meeweel/data/responsemodels/TaskResponse.kt

2022-08-16 17:27 UTC, MeeWeeL commented on app/src/main/java/com/meeweel/anilist/data/room/Mapping.kt
>  //fun convertResponseToAnime(anime: AnimeResponse) : Anime {
Удаляй комментарии

2022-08-17 16:38 UTC, MeeWeeL approved these changes

2022-08-18 08:55 UTC, SquareBrains approved these changes

2022-08-18 08:59 UTC, SquareBrains approved these changes

2022-08-18 09:52 UTC, merged