t1005. Интерфейс выставления оценок
MeeWeeL/AnimeListOnKotlin pull request #21
Opened 2022-08-19 19:51 UTC by Elena01001

2022-08-19 20:12 UTC, MeeWeeL requested changes

2022-08-19 20:12 UTC, MeeWeeL commented on app/src/main/java/com/meeweel/anilist/ui/fragments/detailsFragment/DetailsFragment.kt
> +                    makeRateScore(animeData.id, 1)
Повторяемый код. В каждом листенере одни и те же 3 строчки кода повторяются, меняется только оценка. Если вынести в функцию, можно избежать повторяемости кода. Котлин дает возможность создания вложенных функций (Функции внутри функций)

2022-08-19 20:12 UTC, MeeWeeL commented on app/src/main/java/com/meeweel/anilist/ui/fragments/detailsFragment/DetailsFragment.kt
> +import android.content.Context
Подозреваю, что этот импорт лишний. Прожми Ctrl+Alt+O (автоматическая оптимизация импортов)

2022-08-19 20:12 UTC, MeeWeeL commented on app/src/main/res/layout/rate_bottom_sheet_layout.xml
> +    android:visibility="visible">
Visibility мы менять не собираемся, а по дефолту он и так Визибл, так что это лишняя строчка

2022-08-19 20:12 UTC, MeeWeeL commented on app/src/main/res/layout/rate_bottom_sheet_layout.xml
> +            android:text="@string/cancel"
Вынесение в стринги одобряю, но я бы слово поменял на Позже/Later

2022-08-19 20:12 UTC, MeeWeeL commented on app/src/main/java/com/meeweel/anilist/ui/fragments/detailsFragment/DetailsFragment.kt
> +
лишняя пустота

2022-08-22 16:54 UTC, MeeWeeL requested changes

2022-08-22 16:54 UTC, MeeWeeL commented on app/src/main/java/com/meeweel/anilist/ui/fragments/detailsFragment/DetailsFragment.kt
> +                    showAnimeRateScore(animeData.id, 1)
Зачем передавать айди даты в аргументы функции? Функция находится в зоне видимости даты. Можешь внутри функции обратиться к ней

2022-08-22 16:54 UTC, MeeWeeL commented on app/src/main/java/com/meeweel/anilist/ui/fragments/detailsFragment/DetailsFragment.kt
> +        fun showAnimeRateScore(id: Int, score: Int) {
Почему называется show? Разве мы что-то показываем этой функцией? Она изменяет рейтинг, а не показывает

2022-08-24 10:56 UTC, SquareBrains submitted a review, later dismissed

2022-08-24 18:11 UTC, merged