t1001. Сохранение состояния фрагментов
MeeWeeL/AnimeListOnKotlin pull request #35
Opened 2022-08-31 18:46 UTC by MeeWeeL

2022-09-01 15:30 UTC, Elena01001 requested changes

2022-09-01 15:30 UTC, Elena01001 commented on app/src/main/java/com/meeweel/anilist/ui/fragments/listFragments/lists/mainFragment/MainFragment.kt
> +    private val binding get() = _binding!!
Что-то часто встречаются восклицательные

2022-09-01 15:30 UTC, Elena01001 commented on app/src/main/java/com/meeweel/anilist/ui/fragments/listFragments/lists/mainFragment/MainFragment.kt
> +    override val adapter: MainFragmentAdapter get() = adapterState!!
И здесь + то же самое в NotWatchedFragment, UnwantedFragment, WantedFragment, WatchedFragment

2022-09-02 18:56 UTC, Elena01001 approved these changes

2022-09-03 09:34 UTC, SquareBrains approved these changes

2022-09-03 19:25 UTC, merged