b5004. Fixed layout for Chinese phones
MeeWeeL/AnimeListOnKotlin pull request #37
Opened 2022-09-01 14:49 UTC by Elena01001

2022-09-02 05:40 UTC, MeeWeeL requested changes

2022-09-02 05:40 UTC, MeeWeeL commented on app/src/main/res/values/styles.xml
> +        <item name="android:ellipsize">end</item>
Этот стиль наследуется от другого стиля. Не проще ли в одном родительском стиле добавить изменения, чем в каждом дочернем тыкаться?

2022-09-02 05:40 UTC, MeeWeeL commented on app/src/main/res/values/styles.xml
> +        <item name="android:textSize">@dimen/_13sp</item>
Этот стиль наследуется от другого стиля. Не проще ли в одном родительском стиле добавить изменения, чем в каждом дочернем тыкаться?

2022-09-02 05:40 UTC, MeeWeeL commented on app/src/main/res/values/styles.xml
> +        <item name="android:textSize">@dimen/_13sp</item>
Этот стиль наследуется от другого стиля. Не проще ли в одном родительском стиле добавить изменения, чем в каждом дочернем тыкаться?

2022-09-02 05:40 UTC, MeeWeeL commented on app/src/main/res/values/styles.xml
> +        <item name="android:textSize">@dimen/_13sp</item>
Этот стиль наследуется от другого стиля. Не проще ли в одном родительском стиле добавить изменения, чем в каждом дочернем тыкаться?

2022-09-02 05:40 UTC, MeeWeeL commented on app/src/main/res/values/styles.xml
> +        <item name="android:textSize">@dimen/_13sp</item>
Этот стиль наследуется от другого стиля. Не проще ли в одном родительском стиле добавить изменения, чем в каждом дочернем тыкаться?

2022-09-02 05:40 UTC, MeeWeeL commented on build.gradle
> +        classpath 'com.android.tools.build:gradle:7.2.1'
Смена версии грэдла это осознанное решение?

2022-09-03 05:46 UTC, MeeWeeL commented on app/src/main/res/values/styles.xml
> +        <item name="android:textSize">@dimen/_13sp</item>
Если красную кнопку изменили, почему не меняем зелёную? Они должны быть однотипные

2022-09-03 08:23 UTC, MeeWeeL approved these changes

2022-09-03 09:34 UTC, SquareBrains approved these changes

2022-09-03 16:30 UTC, merged